name: OneStopShop
main: lee.code.onestopshop.OneStopShop
version: ${project.version}
api-version: 1.13
author: Lee
softdepend: [Vault, Essentials, SunLight, SimplisticEconomy, CMI]
commands:
  shop:
    description: Opens shop menu.
    permission: oss.shop.use
    aliases: [shops]